### ISSUE TITLE
Flaky test in xrpc-server stream test suite

### ISSUE THREAD

**Issue by devinivy** [bluesky-social/atproto#1253]
https://github.com/bluesky-social/atproto/actions/runs/5415976300/jobs/9845048475?pr=1231

```
@atproto/xrpc-server: FAIL XRPC Server tests/stream.test.ts
@atproto/xrpc-server:   Stream
@atproto/xrpc-server:     ✓ streams message and info frames. (88 ms)
@atproto/xrpc-server:     ✓ kills handler and closes on error frame. (100 ms)
@atproto/xrpc-server:     ✕ kills handler and closes client disconnect. (31 ms)
@atproto/xrpc-server:     byMessage()
@atproto/xrpc-server:       ✓ kills handler and closes client disconnect on error frame. (22 ms)
@atproto/xrpc-server:   ● Stream › kills handler and closes client disconnect.
@atproto/xrpc-server:     expect(received).toBe(expected) // Object.is equality
@atproto/xrpc-server:     Expected: 5
@atproto/xrpc-server:     Received: 6
@atproto/xrpc-server:       116 |     const currentCount = i
@atproto/xrpc-server:       117 |     await wait(5)
@atproto/xrpc-server:     > 118 |     expect(i).toBe(currentCount)
@atproto/xrpc-server:           |               ^
@atproto/xrpc-server:       119 |
@atproto/xrpc-server:       120 |     httpServer.close()
@atproto/xrpc-server:       121 |   })
@atproto/xrpc-server:       at Object.toBe (tests/stream.test.ts:118:15)
@atproto/xrpc-server:   console.error
@atproto/xrpc-server:     Error: request entity too large
@atproto/xrpc-server:         at MaxSizeChecker.createError (/home/runner/work/atproto/atproto/packages/xrpc-server/src/util.ts:262:13)
@atproto/xrpc-server:         at MaxSizeChecker.createError [as _transform] (/home/runner/work/atproto/atproto/packages/common/src/streams.ts:62:32)
@atproto/xrpc-server:         at MaxSizeChecker.Transform._write (node:internal/streams/transform:175:8)
@atproto/xrpc-server:         at writeOrBuffer (node:internal/streams/writable:392:12)
@atproto/xrpc-server:         at _write (node:internal/streams/writable:333:10)
@atproto/xrpc-server:         at MaxSizeChecker.Writable.write (node:internal/streams/writable:337:10)
@atproto/xrpc-server:         at IncomingMessage.ondata (node:internal/streams/readable:766:22)
@atproto/xrpc-server:         at IncomingMessage.emit (node:events:513:28)
@atproto/xrpc-server:         at IncomingMessage.Readable.read (node:internal/streams/readable:539:10)
@atproto/xrpc-server:         at flow (node:internal/streams/readable:1023:34)
@atproto/xrpc-server:       at Function.error (../../node_modules/express/lib/application.js:647:43)
```

**Comment by devinivy** [comment]
Haven't observed this in ages, closing!
