### ISSUE TITLE
Reaching end of listRepos crashes validation

### ISSUE THREAD

**Issue by mihailik** [bluesky-social/atproto#1949]
**Calling listRepos, crashing on last page of response**

[reported on BlueSky earlier](https://bsky.app/profile/oyin.bo/post/3kg5ermhhuc2u)

Calling com.atproto.sync.listRepos via JavaScript client crashes on the last page (and also on the last page see #1948 ).

**To Reproduce**

Steps to reproduce the first behavior:

1. Call listRepos in a normal way, without cursor or pass `"3516308"` string as a cursor.
2. It blows: `ValidationError: Output/repos must be an array`

Sample code:

```js
async function tryListReposEnd() {
  const atClient = new atproto.BskyAgent({
    // service: 'https://bsky.social/xrpc'
    service: 'https://bsky.network/xrpc'
  });

  const reply = await atClient.com.atproto.sync.listRepos({ cursor: 3516308, limit: 997 });
  console.log(reply);
}
```

Exact failure:

```
XRPCInvalidResponseError: The server gave an invalid response and may be out of date.       
    at ServiceClient.call (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:15634:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async tryListReposEnd (C:\Users\mihai\oyin.bo\bluesky-static\accounts\scripts\crash1.js:23:17) {
  status: 2,
  error: 'Invalid Response',
  success: false,
  headers: undefined,
  lexiconNsid: 'com.atproto.sync.listRepos',
  validationError: ValidationError: Output/repos must be an array
      at array (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:14697:14)
      at validate2 (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:14683:14)
      at validateOneOf (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:14811:78)
      at object (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:14745:25)
      at validateOneOf (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:14811:32)
      at assertValidOneOf (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:14826:15)
      at assertValidXrpcOutput (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:15172:12)
      at Lexicons.assertValidXrpcOutput (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:15278:12)
      at ServiceClient.call (C:\Users\mihai\oyin.bo\bluesky-static\accounts\node_modules\@atproto\api\dist\index.js:15631:29)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5),        
  responseBody: { repos: null }
}
```

You can see above, the actual server response has `null` value in `repos` field and no `cursor`, indicating this is the end of the list:

```js
{ "repos": null }
```

**Expected behavior**

Don't blow up, it is fine.

Client library **should** tolerate variety of server responses: whether it's an explicit `null`, and empty array `[]`, or `undefined` in that field, just accept there are no repositories in this response and keep moving.

**Details**

- Operating system: Windows
- Node version: 20
- \@atproto/api: "^0.7.2"  (current now, and published a day ago)
- service: https://bsky.network/xrpc

Can also observe the dodgy data by opening this in browser, look at the bottom of the page:

https://bsky.network/xrpc/com.atproto.sync.listRepos?cursor=3000000

![image](https://github.com/bluesky-social/atproto/assets/4041967/60e6b70a-b393-4fa8-9da9-4acf77643741)

**Additional context**

This crash happens on the very last page of `listRepos`, and there is another one reported for the very first first page.

Feels like the validation really needs to be relaxed a bit for the client API library. These issues are very spurious.

**Comment by mihailik** [comment]
As a workaround, see [._service.xrpc.baseClient.lex.assertValidXrpcOutput patch](https://github.com/bluesky-social/atproto/issues/1948#issuecomment-1853688635) in #1948 description.

**Comment by bnewbold** [comment]
IMO this is mostly a Relay bug, not a client-side bug. `repos` should not be `null`, it should be an empty array; the client package is doing a reasonable thing when it throws an exception on this.

I created a PR in the relay code (golang) for this specific endpoint, though it is likely a more systemic issue on that end.
