### ISSUE TITLE
XRPCError: XRPC Not Supported

### ISSUE THREAD

**Issue by fishcharlie** [bluesky-social/atproto#1954]
**Describe the bug**

`XRPCError: XRPC Not Supported` error.

Full stack trace:

```
/project/node_modules/@atproto/api/dist/index.js:15639
        throw new XRPCError(resCode);
              ^

XRPCError: XRPC Not Supported
    at ServiceClient.call (/project/node_modules/@atproto/api/dist/index.js:15639:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BskyAgent.login (/project/node_modules/@atproto/api/dist/index.js:27009:19)
    at async postToBluesky (/project/dist/index.js:67:5)
    at async Promise.all (index 1)
    at async /project/dist/index.js:46:5 {
  status: 404,
  error: 'XRPCNotSupported',
  success: false,
  headers: undefined
}
```

**To Reproduce**

1. Run the following code
2. Notice the error

```ts
const bskyAgent = new BskyAgent({
	"service": "https://bsky.app"
});
async function postToBluesky(content: string) {
	await bskyAgent.login({
		"identifier": config.bluesky?.username ?? "",
		"password": config.bluesky?.password ?? ""
	});

	const rt = new RichText({
		"text": content
	});
	await rt.detectFacets(bskyAgent);
	const postRecord = {
		"text": rt.text,
		"facets": rt.facets
	};
	await bskyAgent.post(postRecord);
}
```

**Expected behavior**

The post to successfully post to Bluesky.

**Details**

- Operating system: macOS 14.1.1
- Node version: 20.10.0

**Additional context**

**Comment by bnewbold** [comment]
I think the issue is that the "service" should be `https://bsky.social`, not `https://bsky.app`.

**Comment by fishcharlie** [comment]
@bnewbold That worked. Thank you so much!
