### ISSUE TITLE
PDS: Error message on failure to open database is unhelpful

### ISSUE THREAD

**Issue by mcclure** [bluesky-social/atproto#2433]
**Describe the bug**

Say one boots the pds server, but it cannot open its files for writing. It will give this very unhelpful error message:

```
Started atproto personal data server.
/var2/www2/bsky/pds/service/node_modules/.pnpm/better-sqlite3@9.4.1/node_modules/better-sqlite3/lib/database.js:69
              [util.cppdb]: { value: new addon.Database(filename, filenameGiven, anonymous, readonly, fileMustExist, timeout, verbose || null, buffer || null) },
                                     ^
SqliteError: unable to open database file
    at new Database (/var2/www2/bsky/pds/service/node_modules/.pnpm/better-sqlite3@9.4.1/node_modules/better-sqlite3/lib/database.js:69:26)
    at Function.sqlite (/var2/www2/bsky/pds/service/node_modules/.pnpm/@atproto+pds@0.4.12/node_modules/@atproto/pds/src/db/db.ts:31:22)
    at getDb (/var2/www2/bsky/pds/service/node_modules/.pnpm/@atproto+pds@0.4.12/node_modules/@atproto/pds/src/did-cache/db/index.ts:16:19)
    at DidSqliteCache (/var2/www2/bsky/pds/service/node_modules/.pnpm/@atproto+pds@0.4.12/node_modules/@atproto/pds/src/did-cache/index.ts:17:20)
    at Function.fromConfig (/var2/www2/bsky/pds/service/node_modules/.pnpm/@atproto+pds@0.4.12/node_modules/@atproto/pds/src/context.ts:130:22)
    at Function.create (/var2/www2/bsky/pds/service/node_modules/.pnpm/@atproto+pds@0.4.12/node_modules/@atproto/pds/src/index.ts:65:34)
    at main (/var2/www2/bsky/pds/service/index.js:16:25)
    at Object.<anonymous> (/var2/www2/bsky/pds/service/index.js:72:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10) {
  code: 'SQLITE_CANTOPEN'
}
```

The error message says it could not open the "database file". However, it does not give the path which it was unable to open. The pds server involves several database files, so it is difficult for a user to act on this error message. I lost quite a bit of time trying to understand what it wanted me to do.

**To Reproduce**

I encountered the error while following [these third-party instructions](https://benharri.org/bluesky-pds-without-docker/). I was able to cause the error by creating the `pds/service/data/blocks` directory (within a checkout of the [pds](https://github.com/bluesky-social/pds) repository) but then setting the ownership/permissions of `data` and `data/blocks` such that the user that would be running the pds server could not read or write them.

Although this error would be less likely to occur organically when using docker as recommended, I believe you could still reproduce the error in docker by setting the file permissions on the `data` directory to something unreasonable such as 000.

**Expected behavior**

[db.ts](https://github.com/bluesky-social/atproto/blob/main/packages/pds/src/db/db.ts), in the static sqlite() function, when calling new SqliteDb(), should catch the `SqliteError(code='SQLITE_CANTOPEN')` and re-throw or otherwise log the error in a way that includes the current value of `location` in the error message. 

**Details**

- Operating system: Ubuntu 20.04.6 LTS
- Node version: v20.12.2

**Comment by bnewbold** [comment]
Thanks for filing! This is indeed an unhelpful message for folks not following the exact setup instructions.

For transparency, we probably won't implement this ourselves one-off until we do a larger iteration on the PDS setup/deploy experience. But we would review PRs for this if you or others are interested in contributing.

**Comment by P3X-118** [comment]
_Although this error would be less likely to organically occur when using docker as recommended, I believe you could still reproduce the error in docker by setting the file permissions on the data directory to something unreasonable such as 000._

Of course it would be me... Working on restricting docker permissions, gave the PDS docker user the wrong guid, and found myself here. 

Simply adding a "check permissions" to the error flag, would go a long way.

**Comment by sakuragasaki46** [comment]
Same issue. Node.js continuously reporting being unable to open database file.

```
/app/node_modules/.pnpm/better-sqlite3@10.1.0/node_modules/better-sqlite3/lib/database.js:65
                throw new TypeError('Cannot open database because the directory does not exist');
                      ^

TypeError: Cannot open database because the directory does not exist
    at new Database (/app/node_modules/.pnpm/better-sqlite3@10.1.0/node_modules/better-sqlite3/lib/database.js:65:9)
    at Function.sqlite (/app/node_modules/.pnpm/@atproto+pds@0.4.138/node_modules/@atproto/pds/src/db/db.ts:31:22)
    at getDb (/app/node_modules/.pnpm/@atproto+pds@0.4.138/node_modules/@atproto/pds/src/did-cache/db/index.ts:16:19)
    at DidSqliteCache (/app/node_modules/.pnpm/@atproto+pds@0.4.138/node_modules/@atproto/pds/src/did-cache/index.ts:17:20)
    at Function.fromConfig (/app/node_modules/.pnpm/@atproto+pds@0.4.138/node_modules/@atproto/pds/src/context.ts:173:22)
    at Function.create (/app/node_modules/.pnpm/@atproto+pds@0.4.138/node_modules/@atproto/pds/src/index.ts:62:34)
    at main (/app/index.js:16:25)
    at Object.<anonymous> (/app/index.js:72:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v20.11.1
```

After digging through source code, I discovered `PDS_DATA_DIRECTORY` needed to be set. I set it to a custom value (`/home/<username>/pds`) instead of the default `/pds` in `pds/pds.env` (located in that data directory, of course). However, that did not help.

Did not follow the installation guide at @bluesky-social/pds by letter because I can't afford to downgrade my system (Ubuntu 24.04, still unsupported!).

Also I installed PDS in custom directory, instead of `/pds`; modified `pdsadmin.sh` to meet my needs for control (including removal of hardcoded `PDS_DATADIR='/pds'` in downloaded scripts); and Apache listens on ports 80 and 443 (instead of Caddy). I am aware those practices may void my right to support.

**Comment by sakuragasaki46** [comment]
@P3X-118 I have changed the mountpoint source to absolute path (was relative) in `compose.yaml` *(for which I keep a copy to prevent accidental overwrite)*.

I have changed `/pds` directory owner to root  — this means I denied my local user permission to do maintenance.

I have `docker compose build`ed several times.

The issue is still there: Nodejs can't find the database.

I need someone to pinpoint the exact line sourcing the database file path to open.

**Comment by sakuragasaki46** [comment]
UPDATE the issue was me changing `PDS_DATA_DIRECTORY=/pds` to my custom value, unknowing that file would be loaded verbatim into the container, where directory layout is different.

Issue solved for me.
