### ISSUE TITLE
Yarn build error on better-sqlite3

### ISSUE THREAD

**Issue by brh28** [bluesky-social/atproto#274]
When executing `yarn` from the root directory, I'm getting the following error:

`error /home/benhindman/Workspace/atproto/packages/pds/node_modules/better-sqlite3, /home/benhindman/Workspace/atproto/packages/plc/node_modules/better-sqlite3: Command failed.`
...
```
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
gyp ERR! stack     at createConfigFile (/home/benhindman/Workspace/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:117:21)
gyp ERR! stack     at /home/benhindman/Workspace/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:84:9
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:189:23)
gyp ERR! System Linux 5.15.0-52-generic
gyp ERR! command "/home/benhindman/.nvm/versions/node/v19.0.0/bin/node" "/home/benhindman/Workspace/atproto/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /home/benhindman/Workspace/atproto/packages/pds/node_modules/better-sqlite3
```

Any troubleshooting tips would be appreciated.

OS: Ubuntu 22.04.1
node: v19.0.0
yarn: 1.22.19

**Comment by brh28** [comment]
Switched to node v18. The build now completes without failing. However, when I run`yarn start` from the `dev-env` directory, I get a `Error: Cannot find module 'better-sqlite3'` so still not sure if the build is running as expected.  

I do believe better-sqlite3 is compatible with my system. At least, I am able to install with `yarn add better-sqlite3` in an empty directory.

BTW, I seeing a console message about upgrading to node v19. Not sure why that would be there

**Comment by brh28** [comment]
Manually added better-sqlite3 in the dev-env dir and the PDS server does startup correctly now. Not sure if I'm going to run into issues down the road though

**Comment by devinivy** [comment]
I am seeing the same thing.  I think I just bonked that a couple hours ago in #272— will take a closer look at it before long.

**Comment by brh28** [comment]
Sounds good. Thanks for the help!

**Comment by dholms** [comment]
yeah these build scripts are pretty error prone, fixed it up here: https://github.com/bluesky-social/atproto/pull/275

**Comment by dholms** [comment]
alright merged that into `main`

heads up @brh28 to get this to work you may have to wipe out the `node_modules` at the repo root & then do reinstall

**Comment by roj1512** [comment]
I have the same problem from a fresh clone and Node.js v20.0.0.

**Comment by jemgold** [comment]
+++ still getting this with a fresh clone & wiped node modules on node 18.14.1, 18.16.0 and 20.0.0. `yarn global add better-sqlite3` works; I don't know enough about node-gyp to know how to debug further or to be able to decipher what's going wrong in the logs.

on an M1 MBP - it looks like better-sqlite3 *does* have a prebuilt binary for arm64 which makes me more confused

example traceback~
```
[5/5] 🔨  Building fresh packages...
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
[3/5] ⡀ cbor-extract
[4/5] ⡀ better-sqlite3
error /Users/jem/code/atproto/atproto/node_modules/better-sqlite3: Command failed.
Exit code: 1
Command: prebuild-install || npm run build-release
Arguments: 
Directory: /Users/jem/code/atproto/atproto/node_modules/better-sqlite3
Output:
prebuild-install warn install No prebuilt binaries found (target=18.16.0 runtime=node arch=arm64 libc= platform=darwin)

> better-sqlite3@7.6.2 build-release
> node-gyp rebuild --release

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@18.16.0 | darwin | arm64
gyp info find Python using Python version 3.11.2 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
(node:73047) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /opt/homebrew/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jem/code/atproto/atproto/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jem/Library/Caches/node-gyp/18.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jem/Library/Caches/node-gyp/18.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jem/Library/Caches/node-gyp/18.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jem/code/atproto/atproto/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
    result = gyp.input.Load(
             ^^^^^^^^^^^^^^^
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
    LoadTargetBuildFile(
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
    build_file_contents = open(build_file_path, "rU").read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jem/code/atproto/atproto/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Users/jem/Library/Application Support/fnm/node-versions/v18.16.0/installation/bin/node" "/Users/jem/code/atproto/atproto/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /Users/jem/code/atproto/atproto/node_modules/better-sqlite3
```

**Comment by roj1512** [comment]
By the way, I have noticed that this problem will not stop you from being able to run the tests and do development.
